server:
  tomcat:
    threads:
      max: 128
      min-spare: 10
    accept-count: 100

spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:public;
      username: sa
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop